apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalogue-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-catalogue-service
  template:
    metadata:
      labels:
        app: movie-catalogue-service
    spec:
      containers:
        - name: movie-catalogue-service
          image: aissambsf/movie-catalogue-service:60
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

