pipeline {
    environment {
        dockerimagename = "aissambsf/movie-catalogue-service"
        dockerImage = ""
      }

    agent any

    stages {
        stage('Checkout Source') {
            steps {
                git 'https://github.com/Bravinsimiyu/jenkins-kubernetes-deployment.git'
            }
        }

        stage('Build Image') {
            steps {
                script {
                    dockerImage = docker.build dockerimagename
                }
            }
        }

        stage('Pushing Image') {
            environment {
                registryCredential = 'dockerhub-credentials'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploying Movie Catalogue Service container to Kubernetes') {
            steps {
                script {
                    kubernetesDeploy(configs:"deployment.yaml", "service.yaml")
                }
            }
        }
    }


}